#!/usr/bin/env python3
"""Compute, check or regenerate the Apex SDK source hash.

The hash is a SHA-256 over every .cs and .asmdef file under Runtime/ (the source of
ApexSystem and everything it compiles against), except the generated files listed in
EXCLUDED. It lets you tell whether two builds contain the same SDK code, independent
of the version number in package.json.

The algorithm must stay in sync with Editor/Script/ApexSourceHash.cs:
  * files are sorted by their package-relative path ('/' separators, ordinal order)
  * a leading UTF-8 BOM is removed and CRLF is converted to LF, so the hash does not
    depend on git's line ending conversion
  * for each file: UTF-8 path bytes, a 0 byte, normalized content bytes, a 0 byte

Usage:
  python3 "Tools~/source_hash.py"          print the hash
  python3 "Tools~/source_hash.py" --check  exit 1 if the generated file is stale
  python3 "Tools~/source_hash.py" --write  regenerate the generated file
"""
import hashlib
import os
import sys

PACKAGE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = "Runtime"
EXTENSIONS = (".cs", ".asmdef")
GENERATED_FILE = "Runtime/SDK/ApexSourceHashGenerated.cs"
EXCLUDED = {GENERATED_FILE, "Runtime/SDK/ApexUtilsGenerated.cs"}


def source_files():
    files = []
    for directory, _, names in os.walk(os.path.join(PACKAGE_ROOT, SOURCE_DIR)):
        for name in names:
            if not name.endswith(EXTENSIONS):
                continue
            path = os.path.relpath(os.path.join(directory, name), PACKAGE_ROOT).replace(os.sep, "/")
            if path not in EXCLUDED:
                files.append(path)
    # Ordinal sort, matching string.CompareOrdinal in C#.
    return sorted(files, key=lambda p: p.encode("utf-16-be"))


def normalize(content):
    if content.startswith(b"\xef\xbb\xbf"):
        content = content[3:]
    return content.replace(b"\r\n", b"\n")


def compute_hash():
    sha = hashlib.sha256()
    for path in source_files():
        with open(os.path.join(PACKAGE_ROOT, path), "rb") as f:
            content = normalize(f.read())
        sha.update(path.encode("utf-8"))
        sha.update(b"\0")
        sha.update(content)
        sha.update(b"\0")
    return sha.hexdigest()


def generated_source(source_hash):
    return (
        "// <auto-generated>\n"
        "// SHA-256 of the SDK Runtime source files. Do not edit by hand: it is regenerated by the\n"
        "// Unity editor when the package is embedded or local, or by running Tools~/source_hash.py --write.\n"
        "// </auto-generated>\n"
        "namespace PixoVR.Apex.Utils { public static partial class ApexUtils { public static string SDKSourceHash => \""
        + source_hash
        + "\"; } }\n"
    )


def main(args):
    source_hash = compute_hash()
    generated_path = os.path.join(PACKAGE_ROOT, GENERATED_FILE)
    expected = generated_source(source_hash)

    if "--write" in args:
        with open(generated_path, "w", newline="\n") as f:
            f.write(expected)
        print(source_hash)
        return 0

    if "--check" in args:
        try:
            with open(generated_path, "rb") as f:
                current = normalize(f.read()).decode("utf-8")
        except FileNotFoundError:
            current = ""
        if current != expected:
            print(f"{GENERATED_FILE} is stale. Expected source hash {source_hash}.")
            print('Run: python3 "Tools~/source_hash.py" --write')
            return 1
        print(f"Source hash is up to date: {source_hash}")
        return 0

    print(source_hash)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
