// <auto-generated>
// SHA-256 of the SDK Runtime source files. Do not edit by hand: it is regenerated by the
// Unity editor when the package is embedded or local, or by running Tools~/source_hash.py --write.
// </auto-generated>
namespace PixoVR.Apex.Utils { public static partial class ApexUtils { public static string SDKSourceHash => "35ef326529945e3db713f53eef73515efe0f826ca02062076a400bc18beae34a"; } }
