// <auto-generated>
// SHA-256 of the SDK Runtime source files. Do not edit by hand: it is regenerated by the
// Unity editor when the package is embedded or local, or by running Tools~/source_hash.py --write.
// </auto-generated>
namespace PixoVR.Apex.Utils { public static partial class ApexUtils { public static string SDKSourceHash => "4cd1351221e2fd8dac3da30b94b3bff54febd3b4bc9e7a0b131ab21621b856a0"; } }
